DROP TABLE deporte CASCADE CONSTRAINTS;
DROP TABLE medalla CASCADE CONSTRAINTS;
DROP TABLE competidor CASCADE CONSTRAINTS;
DROP TABLE deportista CASCADE CONSTRAINTS;
DROP TABLE entrenador CASCADE CONSTRAINTS;

DROP TYPE distancia_table FORCE
/
DROP TYPE deporte_t FORCE
/
DROP TYPE medalla_t FORCE
/
DROP TYPE competidor_t FORCE
/
DROP TYPE entrenador_t FORCE
/
DROP TYPE deportista_t FORCE
/
DROP TYPE disciplina FORCE
/
DROP TYPE distancia_t FORCE
/
